---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-k8s
  namespace: default
type: "kubernetes.io/rbd"
data:
  key: QVFCY2EweGZIMklHREJBQWd3M0t0TmVaai9uWk05dlNuMGV0V3c9PQ== # ceph auth print-key client.k8s | base64
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-rbd-vol2
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 86400"]
    volumeMounts:
    - name : rbdpod
      mountPath: /data
  volumes:
    - name: rbdpod
      rbd:
        monitors:
        - '172.18.0.41:6789'
        - '172.18.0.42:6789'
        - '172.18.0.43:6789'
        pool: rbddata
        image: myimg2
        fsType: ext4
        readOnly: false
        user: k8s
        secretRef:
          name: ceph-secret-k8s
